/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ANTHROPIC_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "TAVILY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WeHaveAgentsAtHomeResponseCache": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
